version: '2'
services:
    cimer-app:
        image: cimer
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://cimer-mysql:3306/cimer?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    cimer-mysql:
        extends:
            file: mysql.yml
            service: cimer-mysql
